

var countries = {  
    "Albania": { description: "Closed to outsiders for much of the 20th century, Albania has long been Mediterranean Europe's enigma. Until fairly recently its rumpled mountains, fortress towns and sparkling beaches were merely a rumour on most travel maps.", cities: "Buenos Aires", name: "1N_xG_lIdVc5zj5e00tdYk0Wc6jb2VkrJ", place:"countries/Albania/albania.html",  },
    "Argentina": { description: "Argentina is a beautiful tropical country that is located in the southern Argentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pportion of South America. The official language of Argentina is Spanish, and most people there speak the Castilian Spanish dialect(Wikipedia)", cities: "Buenos Aires", name: "1GS4qNC4F_8ih8tk-7syaJY4jCqjJSnJU", place: "countries/Argentina/argentina.html",  },
    "Australia": { description: "Australia, officially the Commonwealth of Australia, is a sovereign country comprising the mainland of the Australian continent, the island of Tasmania and numerous smaller islands. It is the largest country in Oceania and the world's sixth-largest country by total area(Wikipedia)", cities: "Buenos Aires", name: "1ChLgC0VOgiOJKPBxvo_oba48-TZzeIgA", place:"countries/Australia/australia.html",  },
    "Austria": { description: " Small, landlocked Austria offers alpine scenery, world-class museums, cobbled quaintness, and Wiener schnitzel. Unlike Germany, its industrious neighbor to the northwest, Austria is content to bask in its good living and elegant, opulent past as the former head of one of Europe's grandest empires. Austrians tend to be relaxed, gregarious people who love the outdoors as much as a good cup of coffee in a café(Wikipedia", cities: "Buenos Aires", name: "13PzquCG0gLAksOyW3U9FCYwWeMPHoHqg", place:"countries/Austria/austria.html",  },
    "The Bahamas": { description: "The Bahamas is regarded as part of the Caribbean, even though the archipelago of over 700 islands and cays, strung together with deep ocean channels and shallow banks, is actually located in the Atlantic and not the Caribbean Sea. For most visitors, The Bahamas' number one attraction is beaches. There is something really special about the powder-soft, limestone-white sands you find here, and the shallow shorelines and kaleidoscope of blues connecting the sea and sky in a seamless horizon(Wikipedia)", cities: "Buenos Aires", name: "1N7kjQ9EYVcQ1_rxnKqKINZZQbs_0Prmt", place:"countries/Bahamas/bahamas.html",  },
    "Barbados": { description: "Fringed by white sandy beaches, sapphire seas and colourful coral reefs, Barbados is the archetypal Caribbean retreat. Off the beaten path this is not: Simon Cowell, Wayne Rooney and Will Smith are amongst the many celebs that have popularised the island, which, alas, has the a-list prices to match. First time visitors can be forgiven for heading straight for the sand. Barbados is endowed with 113km (70 miles) of glorious beaches, which range from calm coves to surf-pounded shorelines. Most tourists flock to the Platinum Coast to the west, which is lined with luxury resorts, spa hotels, sophisticated restaurants and manicured golf courses, all lapped by the limpid Caribbean Sea. Although Barbados’s interior is unremarkable compared to some of its Caribbean neighbours there is much to see. And the best way to see it is by hiring a motorbike or a jeep and taking to the road, calling at crumbling sugar mills, rum distilleries and traditional churches that look like they’ve been lifted from England. Finish up in the colonial capital, Bridgetown, which, along with the nearby garrison, was awarded World Heritage Site status in 2012(Wikipedia)", cities: "Buenos Aires", name: "1gqLfKeF536LYYb8-wgv7Cw42XpS5aBZM", place:"countries/Barbados/barbados.html",  },
    "Belgium": { description: "Belgium, a country in Western Europe, is known for medieval towns, Renaissance architecture and as headquarters of the European Union and NATO. The country has distinctive regions including Dutch-speaking Flanders to the north, French-speaking Wallonia to the south and a German-speaking community to the east. The bilingual capital, Brussels, has ornate guildhalls at Grand-Place and elegant art-nouveau buildings(Wikipedia)", cities: "Buenos Aires", name: "1GfcPMoX5_oh1Vq38L3hrrPFsRi76ApS0", place:"countries/Belgium/belgium.html",  },
    "Bolivia": { description: " Bolivia is a country in central South America, with a varied terrain spanning Andes Mountains, the Atacama Desert and Amazon Basin rainforest. At more than 3,500m, its administrative capital, La Paz, sits on the Andes’ Altiplano plateau with snow-capped Mt. Illimani in the background. Nearby is glass-smooth Lake Titicaca, the continent’s largest lake, straddling the border with Peru(Wikipedia)", cities: "Buenos Aires", name: "1erXPz4RzndUjAH3e5xnyg44qIdLcIDNV", place:"countries/Bolivia/bolivia.html", },
    "Brazil": { description: "  The world's fifth-largest country commandeers the lion's share of South America, all the way from the Amazon Basin – the world's largest tropical rainforest – to the pampas of southernmost Rio Grande do Sul, delivering 7500kms of sun-toasted sands in between. It is these postcard-perfect shores for which Brazil is arguably most famous, but this Latin giant boasts far more than beaches. Lush jungle? Check. Colonial villages? Check. Unparalleled wildlife? Check. Delectable restaurants and pulse-pumping nightlife? Check. Stunning waterfalls, canyons, mountains and dunescapes? Pronto, pronto, pronto and pronto!(wikipedia)", cities: "Buenos Aires", name: "1uB7Cd_bKwouQG-13_nSfU4vK2WL6kVyy", place:"countries/Brazil/brazil.html",  },
    "Brunei": { description: " Brunei travel guide, including map of Brunei, top Brunei travel experiences, and tips for travel in Brunei and Dubai. Brunei is a tiny, tranquil enclave on the north coast of Borneo. The residents of this wealthy country have a quality of life like no other – thanks to its massive offshore oil and gas deposits, education and healthcare are free, and houses, cars and even pilgrimages to Mecca are subsidised. Brunei is a country of lavish contrasts: the capital of Bandar Seri Begawan (BSB) is a mix of extravagant mosques and traditional wooden houses built on stilts. You can spend a weekend living the life of a sultan in one of Brunei's luxury hotels before trudging, waist-deep in murky water, through pristine, virgin rainforest. Brunei may see itself as an oil state, but it is far from being a mini Dubai. Its wealth is reflected in the happiness and welfare of its people rather than ultra-modern skyscrapers, so the atmosphere is relaxed and calm(Wikipedia)", cities: "Buenos Aires", name: "1I4DwsuOJ3zS9mV-k_dmapO6gQEB1NQV9", place:"countries/Brunei/brunei.html",  },
    "Bulgaria": { description: "Bulgaria is a mixture of old and new, Bulgaria gives travellers a chance to explore a vibrant and attractive part of the Balkans that boasts rich folklore traditions mixed with a variety of stimulating activities. Marketed as an affordable alternative to the Eurozone, Bulgaria draws more and more visitors to its ski-slopes each winter. Its long, sandy Black Sea beaches are becoming an increasingly popular summer destination. But there is much more to Bulgaria than its cheap resorts. Outside of the ski-season, Bulgaria’s mountains and forests make an exciting playground for hikers, trekkers, climbers, mountain-bikers and horse-riders. Nature-enthusiasts will find a vast range of flora and fauna, thanks to Bulgaria’s mix of continental, Mediterranean and steppe terrain, with birds, butterflies and bats being particularly numerous. And it’s well-worth exploring Bulgaria’s timber-framed heritage villages and historic towns, where you’ll find a lively mix of Ottoman mosques, Orthodox Churches and Roman ruins(Wikipedia)", cities: "Buenos Aires", name: "1kTLj6KCuU4TENiEjLhWwkC7-exHFHRqh", place:"countries/Bulgaria/bulgaria.html",  },
    "Cabo Verde": { description: "Cape Verde, or Cabo Verde, is a nation on a volcanic archipelago off the northwest coast of Africa. It’s known for its Creole Portuguese-African culture, traditional morna music and numerous beaches. Its largest island, Santiago, is home to the current capital, Praia. Santiago is also home to the old capital, Cidade Velha, with clifftop fortress Forte Real de São Felipe(Wikipedia)", cities: "Buenos Aires", name: "11ULBql3eAtZae_JuQeprgMKX1VSpIgTp", place:"countries/CaboVerde/cabo-verde.html",  },
    "Cameroon": { description: "Cameroon, on the Gulf of Guinea, is a Central African country of varied terrain and wildlife. Its inland capital, Yaoundé, and its biggest city, the seaport Douala, are transit points to ecotourism sites as well as beach resorts like Kribi – near the Chutes de la Lobé waterfalls, which plunge directly into the sea – and Limbe, where the Limbe Wildlife Centre houses rescued primates(Wikipedia)", cities: "Buenos Aires", name: "1X77_Ieu2cNapongZcyO9eqpNnBd6Wurt", place:"countries/Cameroon/cameroon.html",  },
    "Chad": { description: " Chad, officially the Republic of Chad, is a landlocked country in north-central Africa. It is bordered by Libya to the north, Sudan to the east, the Central African Republic to the south, Cameroon and Nigeria to the southwest, and Niger to the west(Wikipedia)", cities: "Buenos Aires", name: "1eGRNiaMOlmsgZD_xbR6-2K7bSAjQhljU", place:"countries/Chad/chad.html",  },
    "Chile": { description: " Chile is a long, narrow country stretching along South America's western edge, with more than 6,000km of Pacific Ocean coastline. Santiago, its capital, sits in a valley surrounded by the Andes and Chilean Coast Range mountains. The city's palm-lined Plaza de Armas contains the neoclassical cathedral and the National History Museum. The massive Parque Metropolitano offers swimming pools, a botanical garden and zoo(Wikipedia)", cities: "Buenos Aires",   name: "1VwhA8uzNLhi_D3WW8qyz5nPRXpLsK-NW", place:"countries/Chile/chile.html", },
    "China": { description: "China is a populous nation in East Asia whose vast landscape encompasses grassland, desert, mountains, lakes, rivers and more than 14,000km of coastline. Capital Beijing mixes modern architecture with historic sites such as the Forbidden City palace complex and Tiananmen Square. Shanghai is a skyscraper-studded global financial center. The iconic Great Wall of China runs east-west across the country's north(Wikipedia)", cities: "Buenos Aires", name: "1Dg8Jkop8QLkjfHI0Ptcd5RR48mqdL5Ao", place:"countries/China/china.html",  },
    "Colombia": { description: "Colombia is a country at the northern tip of South America. It's landscape is marked by rainforests, Andes mountains and numerous coffee plantations. In the high-altitude capital, Bogotá, the Zona Rosa district is known for its restaurants and shops. Cartagena, on the Caribbean coast, has a walled colonial Old Town, a 16th-century castle and nearby coral reefs(Wikipedia)", cities: "Buenos Aires",  name: "1rkuwpKuO0fmLbeD_PzCr_JqmSU3ljNFo", place:"countries/Colombia/colombia.html", },
    "Costa Rica": { description: "Costa Rica is a rugged, rainforested Central American country with coastlines on the Caribbean and Pacific. Though its capital, San Jose, is home to cultural institutions like the Pre-Columbian Gold Museum, Costa Rica is known for its beaches, volcanoes, and biodiversity. Roughly a quarter of its area is made up of protected jungle, teeming with wildlife including spider monkeys and quetzal birds(Wikipedia)", cities: "Buenos Aires", name: "1A5hqSlfhIo8x6d7VdExCS_WQZGBo56g_", place:"countries/CostaRica/costa-rica.html",  },
    "Croatia": { description: "Despite spending the last decade as Europe’s fastest-rising holiday destination, Croatia still doesn’t feel like a place that has been thoroughly worked over by the tourist industry. With new developments kept on a human scale and businesses retaining a pronounced local flavour, the Adriatic coast emphatically retains a unique character. Whether you’re interested in unspoiled Mediterranean islands, edgy urban culture, Game of Thrones location tours or simply splashing around in the Adriatic’s famously clear waters, Croatia is a place to discover many different landscapes and experiences(Wikipedia)", cities: "Buenos Aires",  name: "1_1wlvEnssGYOup6RDG_ywVeLm0FnyIby", place:"countries/Croatia/croatia.html", },
    "Cuba": { description: "Cuba, officially the Republic of Cuba, is a country comprising the island of Cuba as well as Isla de la Juventud and several minor archipelagos. Cuba is located in the northern Caribbean where the Caribbean Sea, Gulf of Mexico and Atlantic Ocean meet(Wikipedia)", cities: "Buenos Aires",  name: "1ftxzAUFqjwxZLyXvDjPb3BJF9dh7CM_m", place:"countries/Cuba/cuba.html", },
    "Cyprus": { description: "Cyprus, officially the Republic of Cyprus, is an island country in the Eastern Mediterranean and the third largest and third most populous island in the Mediterranean, located south of Turkey, west of Syria and Lebanon, northwest of Israel, north of Egypt, and southeast of Greece(Wikipedia)", cities: "Buenos Aires", name: "1dAHX7Yw04i6C2AO-k_Wqqyd1fLdNFiuH", place:"countries/Cyprus/cyprus.html", },
    "Czech Republic": { description: "The Czech Republic, in Central Europe, is a country that's known for its ornate castles, native beers and long history. Prague, the capital, is home to grand 9th-century Prague Castle, a preserved medieval old town and statue-lined Charles Bridge. Český Krumlov, a small town in the South Bohemia region, is notable for its wealth of Gothic, Renaissance and Baroque buildings, many of which house restaurants and shops.(Wikipedia)", cities: "Buenos Aires" , name: "1UMwSAvxh6vs6pQzavO09B6iYQslhCLiH", place:"countries/CzechRepublic/czech-republic.html", },
    "Denmark": { description: "Denmark is a Scandinavian country comprising the Jutland Peninsula and numerous islands. It's linked to nearby Sweden via the Öresund bridge. Copenhagen, its capital, is home to royal palaces and colorful Nyhavn harbor, plus the Tivoli amusement park and the iconic “Little Mermaid” statue. Odense is writer Hans Christian Andersen’s hometown, with a medieval core of cobbled streets and half-timbered houses.(Wikipedia)", cities: "Buenos Aires", name: "1wVB9W4EXDThiPTtmqUhEb1i474fCM270", place:"countries/Denmark/denmark.html",  },
    "Dominican Republic": { description: "The Dominican Republic is a Caribbean nation that shares the island of Hispaniola with Haiti to the west. It's known for its beaches, resorts and golfing. Its terrain comprises rainforest, savannah and highlands, including Pico Duarte, the Caribbean’s tallest mountain. Capital city Santo Domingo has Spanish landmarks like the Gothic Catedral Primada de America dating back 5 centuries in its Zona Colonial district(Wikipedia)", cities: "Buenos Aires", name: "1Qc3aTbXRXHr3IVGhhgbKD5vjoPdqLMus", place:"countries/DominicanRepublic/dominicana-republic.html",},
    "Ecuador": { description: "Ecuador is a country straddling the equator on South America’s west coast. Its diverse landscape encompasses Amazon jungle, Andean highlands and the wildlife-rich Galápagos Islands. In the Andean foothills at an elevation of 2,850m, Quito, the capital, is known for its largely intact Spanish colonial center, with decorated 16th- and 17th-century palaces and religious sites, like the ornate Compañía de Jesús Church(Wikipedia)", cities: "Buenos Aires", name: "1WXAJT_xlMwfvYPbfnBcawwG02O0w9x9d", place:"countries/Ecuador/ecuador.html",    },
    "Egypt": { description: "Egypt, a country linking northeast Africa with the Middle East, dates to the time of the pharaohs. Millennia-old monuments sit along the fertile Nile River Valley, including Giza's colossal Pyramids and Great Sphinx as well as Luxor's hieroglyph-lined Karnak Temple and Valley of the Kings tombs. The capital, Cairo, is home to Ottoman landmarks like Muhammad Ali Mosque and the Egyptian Museum, a trove of antiquities(Wikipedia)", cities: "Buenos Aires", name: "17c1wu8579WduM2e37cx1wfKhGNPS2lkn", place:"countries/Egypt/egypt.html",  },
    "El Salvador": { description: "El Salvador is a small Central American nation. It's known for its Pacific Ocean beaches, surf spots and mountainous landscape. Its Ruta de Las Flores is a winding route past coffee farms, rainforests with waterfalls and towns like Juayua, with its weekend food festival, plus Ataco, home to vivid murals. The capital, San Salvador, with a dramatic backdrop of volcanoes, has numerous museums and the National Theater(Wikipedia)", cities: "Buenos Aires", name: "10U_Wc1_sXacbDSOlnpWFcpQFjyluQLVg", place:"countries/ElSalvado/el-salvador.html",  },
    "France": { description: "France, in Western Europe, encompasses medieval cities, alpine villages and Mediterranean beaches. Paris, its capital, is famed for its fashion houses, classical art museums including the Louvre and monuments like the Eiffel Tower. The country is also renowned for its wines and sophisticated cuisine. Lascaux’s ancient cave drawings, Lyon’s Roman theater and the vast Palace of Versailles attest to its rich history(Wikipedia)", cities: "Buenos Aires", name: "1f84jkh2us0iCHLXTGSVFeOadmDCiXmc2", place:"countries/France/france.html",  },
    "Germany": { description: "Germany is a Western European country with a landscape of forests, rivers, mountain ranges and North Sea beaches. It has over 2 millennia of history. Berlin, its capital, is home to art and nightlife scenes, the Brandenburg Gate and many sites relating to WWII. Munich is known for its Oktoberfest and beer halls, including the 16th-century Hofbrauhaus. Frankfurt, with its skyscrapers, houses the European Central Bank(Wikipedia)", cities: "Buenos Aires", name: "1D8hB-fkL8IGoTyqvdr_gIDsAt7hdZX7s", place:"countries/Germany/germany.html",  },
    "Greece": { description: "Greece is a country in southeastern Europe with thousands of islands throughout the Aegean and Ionian seas. Influential in ancient times, it's often called the cradle of Western civilization. Athens, its capital, retains landmarks including the 5th-century B.C. Acropolis citadel with the Parthenon temple. Greece is also known for its beaches, from the black sands of Santorini to the party resorts of Mykonos(Wikipedia)", cities: "Buenos Aires", name: "1Wt1mbSABzf83XOL5M1l6KAsiwcZzw9S9", place:"countries/Greece/greece.html",  },
    "Haiti": { description: " Haiti is a Caribbean country that shares the island of Hispaniola with the Dominican Republic to its east. Though it’s still recovering from a 2010 earthquake, many of Haiti's landmarks dating to the early 19th century remain intact. These include Citadelle la Ferriere, a mountaintop fortress, and the nearby ruins of Sans-Souci Palace, the baroque former royal home of King Henry I(Wikipedia)", cities: "Buenos Aires", name: "1GR5qFf-ysI1Q-A8c3vsYFjtGDYQTdZ0l", place:"countries/Haiti/haiti.html",  },
    "Hungary": { description: "Hungary is a landlocked country in Central Europe. Its capital, Budapest, is bisected by the Danube River. Its cityscape is studded with architectural landmarks from Buda’s medieval Castle Hill and grand neoclassical buildings along Pest’s Andrassy Avenue to the 19th-century Chain Bridge. Turkish and Roman influence on Hungarian culture includes the popularity of mineral spas, including at thermal Lake Heviz(Wikipedia)", cities: "Buenos Aires", name: "1M7bIAlqdQ7oUnDNCuLwxJtxQP3dDgQDi", place:"countries/Hungary/hungary.html",  },
    "Iceland": { description: "Iceland, a Nordic island nation, is defined by its dramatic landscape with volcanoes, geysers, hot springs and lava fields. Massive glaciers are protected in Vatnajokull and Sn?fellsjokull national parks. Most of the population lives in the capital, Reykjavik, which runs on geothermal power and is home to the National and Saga museums, tracing Iceland’s Viking history(Wikipedia)", cities: "Buenos Aires", name: "1NP46ucav17F4PPCAGTymjbqylrLvACJd", place:"countries/Iceland/iceland.html",  },
    "India": { description: " India is a vast South Asian country with diverse terrain – from Himalayan peaks to Indian Ocean coastline – and history reaching back 5 millennia. In the north, Mughal Empire landmarks include Delhi’s Red Fort complex and massive Jama Masjid mosque, plus Agra’s iconic Taj Mahal mausoleum. Pilgrims bathe in the Ganges in Varanasi, and Rishikesh is a yoga centre and base for Himalayan trekking(Wikipedia)", cities: "Buenos Aires", name: "1uwVz1GaxnBvXavXK1lABHJ5cI8m7CTaT", place:"countries/India/india.html",  },
    "Indonesia": { description: "Indonesia, a Southeast Asian nation made up of thousands of volcanic islands, is home to hundreds of ethnic groups speaking many different languages. It’s known for beaches, volcanoes, Komodo dragons and jungles sheltering elephants, orangutans and tigers. On the island of Java lies Indonesia's vibrant, sprawling capital, Jakarta, and the city of Yogyakarta, known for gamelan music and traditional puppetry(Wikipedia)", cities: "Buenos Aires", name: "12o1u-dTzRYmkrKuSPr1MpYhCTdYlYY3q", place:"countries/Indonesia/indonesia.html",  },
    "Ireland": { description: "The Republic of Ireland occupies most of the island of Ireland, off the coast of England and Wales. Its capital, Dublin, is the birthplace of writers like Oscar Wilde, and home of Guinness beer. The 9th-century Book of Kells and other illustrated manuscripts are on show in Dublin’s Trinity College Library. Dubbed the \"Emerald Isle\" for its lush landscape, the country is dotted with castles like medieval Cahir Castle(Wikipedia)", cities: "Buenos Aires", name: "1S4poEhLzTS6B0M0UTMU3qxn_SktrYlfK", place:"countries/Ireland/ireland.html",  },
    "Isreal": { description: "Israel, a Middle Eastern country on the Mediterranean Sea, is regarded by Jews, Christians and Muslims as the biblical Holy Land. Its most sacred sites are in Jerusalem. Within its Old City, the Temple Mount complex includes the Dome of the Rock shrine, the historic Western Wall, Al-Aqsa Mosque and the Church of the Holy Sepulchre. Israel's financial hub, Tel Aviv, is known for its Bauhaus architecture and beaches(Wikipedia)", cities: "Buenos Aires", name: "1AF7gi2UXOt-BzTYvkn8AknCkZM1NmTUC", place:"countries/Isreal/isreal.html",  },
    "Italy": { description: "Italy, a European country with a long Mediterranean coastline, has left a powerful mark on Western culture and cuisine. Its capital, Rome, is home to the Vatican as well as landmark art and ancient ruins. Other major cities include Florence, with Renaissance masterpieces such as Michelangelo’s \"David\" and Brunelleschi's Duomo; Venice, the city of canals; and Milan, Italy’s fashion capital(Wikipedia)", cities: "Buenos Aires", name: "1sSaTcWRCvJNCbx9zVD0ZnEswhzpQd5EQ", place:"countries/Italy/italy.html",  },
    "Japan": { description: "Japan is an island country in East Asia. Located in the Pacific Ocean, it lies off the eastern coast of the Asian continent and stretches from the Sea of Okhotsk in the north to the East China Sea and the Philippine Sea in the south(Wikipedia)", cities: "Buenos Aires", name: "1OD3gfe6IfmbCwVhJ8jOrSXxPWKsFe183", place:"countries/Japan/japan.html",  },
    "Luxembourg": { description: "Luxembourg is a small European country, surrounded by Belgium, France and Germany. It’s mostly rural, with dense Ardennes forest and nature parks in the north, rocky gorges of the Mullerthal region in the east and the Moselle river valley in the southeast. Its capital, Luxembourg City, is famed for its fortified medieval old town perched on sheer cliffs(Wikipedia)", cities: "Buenos Aires", name: "1ZIgj3oClRpWFcvgZdcWMW9jFfK6YdlFR", place:"countries/Luxembourg/luxembourg.html",  },
    "Malta": { description: "Malta is an archipelago in the central Mediterranean between Sicily and the North African coast. It's a nation known for historic sites related to a succession of rulers including the Romans, Moors, Knights of Saint John, French and British. It has numerous fortresses, megalithic temples and the Ħal Saflieni Hypogeum, a subterranean complex of halls and burial chambers dating to circa 4000 B.C.(Wikipedia)", cities: "Buenos Aires", name: "1R4g-Ss6LnKwpRVvEXczAEboqp_1izVNN", place:"countries/Malta/malta.html",  },
    "Mexico": { description: " Mexico is a country between the U.S. and Central America that's known for its Pacific and Gulf of Mexico beaches and its diverse landscape of mountains, deserts and jungles. Ancient ruins such as Teotihuacán and the Mayan city of Chichén Itzá are scattered throughout the country, as are Spanish colonial-era towns. In capital Mexico City, upscale shops, renowned museums and gourmet restaurants cater to modern life(Wikipedia)", cities: "Buenos Aires", name: "1MO4tGHgO3jHvVS2Jtw4lp1SuGNzD67xK", place:"countries/Mexico/mexico.html",  },
    "Monaco": { description: "Monaco is a tiny independent city-state on France’s Mediterranean coastline known for its upscale casinos, yacht-lined harbor and prestigious Grand Prix motor race, which runs through Monaco’s streets once a year. Monte-Carlo, its major district, is home to an elegant belle-époque casino complex and ornate Salle Garnier opera house. It also has many luxe hotels, boutiques, nightclubs and restaurants(Wikipedia)", cities: "Buenos Aires", name: "1XXFL-FQaF8mvI49Cine3Jw1FOFW34w2c", place:"countries/Monaco/monaco.html",  },
    "Morocco": { description: " Morocco, a North African country bordering the Atlantic Ocean and Mediterranean Sea, is distinguished by its Berber, Arabian and European cultural influences. Marrakesh’s medina, a mazelike medieval quarter, offers entertainment in its Djemaa el-Fna square and souks (marketplaces) selling ceramics, jewelry and metal lanterns. The capital Rabat’s Kasbah of the Udayas is a 12th-century royal fort overlooking the water(Wikipedia)", cities: "Buenos Aires", name: "11VR79uz3hkmVIukM9aef5G6ERc84G3ZM", place:"countries/Morocco/morocco.html",  },
    "Netherlands": { description: "The Netherlands, a country in northwestern Europe, is known for a flat landscape of canals, tulip fields, windmills and cycling routes. Amsterdam, the capital, is home to the Rijksmuseum, Van Gogh Museum and the house where Jewish diarist Anne Frank hid during WWII. Canalside mansions and a trove of works from artists including Rembrandt and Vermeer remain from the city's 17th-century \"Golden Age\"(Wikipedia)", cities: "Buenos Aires", name: "1kocO4EKzZ-yPghgUHiMu5hoJS264uFFT", place:"countries/Netherlands/netherlands.html",  },
    "New Zealand": { description: "New Zealand is a country in the southwestern Pacific Ocean consisting of 2 main islands, both marked by volcanoes and glaciation. Capital Wellington, on the North Island, is home to Te Papa Tongarewa, the expansive national museum. Wellington’s dramatic Mt. Victoria, along with the South Island’s Fiordland and Southern Lakes, stood in for mythical Middle Earth in Peter Jackson’s \"Lord of the Rings\" films(Wikipedia)", cities: "Buenos Aires", name: "1ecoH5NWOc8Bk0i_SEgG_3k-Wbghij0nr", place:"countries/NewZealand/new-zealand.html",  },
    "Norway": { description: "Norway is a Scandinavian country encompassing mountains, glaciers and deep coastal fjords. Oslo, the capital, is a city of green spaces and museums. Preserved 9th-century Viking ships are displayed at Oslo’s Viking Ship Museum. Bergen, with colorful wooden houses, is the starting point for cruises to the dramatic Sognefjord. Norway is also known for fishing, hiking and skiing, notably at Lillehammer’s Olympic resort(Wikipedia)", cities: "Buenos Aires", name: "1tMdmfZiHOEa9RaRn9-oxZzMyxNRKYXRf", place:"countries/Norway/norway.html",  },
    "Peru": { description: " Peru is a country in South America that's home to a section of Amazon rainforest and Machu Picchu, an ancient Incan city high in the Andes mountains. The region around Machu Picchu, including the Sacred Valley, Inca Trail and colonial city of Cusco, is rich in archaeological sites. On Peru’s arid Pacific coast is Lima, the capital, with a preserved colonial center and important collections of pre-Columbian art(Wikipedia)", cities: "Buenos Aires", name: "1cetwKjRCA4Mlm77-XYpmaQlQWy3clgCs", place:"countries/Peru/peru.html",  },
    "Portugal": { description: "Portugal is a southern European country on the Iberian Peninsula, bordering Spain. Its location on the Atlantic Ocean has influenced many aspects of its culture: salt cod and grilled sardines are national dishes, the Algarve's beaches are a major destination and much of the nation’s architecture dates to the 1500s–1800s, when Portugal had a powerful maritime empire(Wikipedia)", cities: "Buenos Aires", name: "1Moejznkz1aCkXCUCIQanQEOOGs_GzZsw", place:"countries/Portugal/portugal.html",  },
    "Russia": { description: " Russia, the world’s largest nation, borders European and Asian countries as well as the Pacific and Arctic oceans. Its landscape ranges from tundra and forests to subtropical beaches. It’s famous for Moscow's Bolshoi and St. Petersburg's Mariinsky ballet companies. St. Petersburg, founded by Russian leader Peter the Great, has the baroque Winter Palace, now housing part of the State Hermitage Museum’s art collection(Wikipedia)", cities: "Buenos Aires", name: "1Ts5CGfRPM1DLX1XxumQ9P5MGgMhFtawu", place:"countries/Russia/russia.html",  },
    "Spain": { description: "Spain, a country on Europe’s Iberian Peninsula, includes 17 autonomous regions with diverse geography and cultures. Capital city Madrid is home to the Royal Palace and Prado museum, housing works by European masters. Segovia has a medieval castle (the Alcázar) and an intact Roman aqueduct. Catalonia’s capital, Barcelona, is defined by Antoni Gaudí’s whimsical modernist landmarks like the Sagrada Família church(Wikipedia)", cities: "Buenos Aires", name: "1RAMMf2vENlDV3Qd1DZncfPzUbtPRiH4V", place:"countries/Spain/spain.html",  },
    "Sweden": { description: "Sweden is a Scandinavian nation with thousands of coastal islands and inland lakes, along with vast boreal forests and glaciated mountains. Its principal cities, eastern capital Stockholm and southwestern Gothenburg and Malmö, are all coastal. Stockholm is built on 14 islands. It has more than 50 bridges, as well as the medieval old town, Gamla Stan, royal palaces and museums such as open-air Skansen(Wikipedia)", cities: "Buenos Aires", name: "1rui3xnZMRhKjRpn34E3zBALJYysoGgzL", place:"countries/Sweden/sweden.html",  },
    "Switzerland": { description: "Switzerland is a mountainous Central European country, home to numerous lakes, villages and the high peaks of the Alps. Its cities contain medieval quarters, with landmarks like capital Bern’s Zytglogge clock tower and Lucerne’s wooden chapel bridge. The country is also known for its ski resorts and hiking trails. Banking and finance are key industries, and Swiss watches and chocolate are world renowned(Wikipedia)", cities: "Buenos Aires", name: "19nc8FwfNWu-Aip8txqVwpTgtTRhEFJ_T", place:"countries/Switzerland/switzerland.html",  },
    "Thailand": { description: " Thailand is a Southeast Asian country. It's known for tropical beaches, opulent royal palaces, ancient ruins and ornate temples displaying figures of Buddha. In Bangkok, the capital, an ultramodern cityscape rises next to quiet canalside communities and the iconic temples of Wat Arun, Wat Pho and the Emerald Buddha Temple (Wat Phra Kaew). Nearby beach resorts include bustling Pattaya and fashionable Hua Hin(Wikipedia)", cities: "Buenos Aires", name: "1MuYQlMOmfC4HbrA8UxvafMg0VMj4aseg", place:"countries/Thailand/thailand.html",  },
    "United Arab Emirates": { description: " The United Arab Emirates is an Arabian Peninsula nation settled mainly along the Persian (Arabian) Gulf. The country is a federation of 7 emirates. Abu Dhabi, the island capital, is home to Sheikh Zayed Grand Mosque, with crystal chandeliers and room for 40,000 worshipers. Dubai is the site of ultramodern Burj Khalifa tower, enormous shopping centers and extravagant entertainment attractions(Wikipedia)", cities: "Buenos Aires", name: "1w8_jas6s-Nzoa8rN35X2q5Efxse9ut6Z", place:"countries/UAE/uae.html",  },
    "United Kingdom": { description: "The United Kingdom, made up of England, Scotland, Wales and Northern Ireland, is an island nation in northwestern Europe. England – birthplace of Shakespeare and The Beatles – is home to the capital, London, a globally influential centre of finance and culture. England is also site of Neolithic Stonehenge, Bath’s Roman spa and centuries-old universities at Oxford and Cambridge(Wikipedia)", cities: "Buenos Aires", name: "1QEEZGOxAFOC40A1WEgWKBxnYpzZwaSAR", place:"countries/UK/uk.html",  },
    "United States": { description: " The U.S. is a country of 51 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles' Hollywood is famed for filmmaking(Wikipedia)", cities: "Buenos Aires", name: "1kiWdnOtawmCuObfg0A7-NCYXaaNJAtj1", place:"countries/usa/usa.html",  },
    "Uruguay": { description: "Uruguay is a South American country known for its verdant interior and beach-lined coast. The capital, Montevideo, revolves around Plaza Independencia, once home to a Spanish citadel. It leads to Ciudad Vieja (Old City), with art deco buildings, colonial homes and Mercado del Puerto, an old port market with many steakhouses. La Rambla, a waterfront promenade, passes fish stalls, piers and parks(Wikipedia)", name: "1PC09BJiYv7oPuhQG7EriAWNT8pGtyPSr", place:"countries/Uruguay/uruguay.html",  },
    "Vatican City": { description: "Vatican City, a city-state surrounded by Rome, Italy, is the headquarters of the Roman Catholic Church. It's home to the Pope and a trove of iconic art and architecture. Its Vatican Museums house ancient Roman sculptures such as the famed “Laocoön and His Sons” as well as Renaissance frescoes in the Raphael Rooms and the Sistine Chapel, famous for Michelangelo’s ceiling(Wikipedia)", cities: "Buenos Aires", name: "17ESi0k7iKqfSTQjpVdcVgddiXhWGjqj6", place:"countries/VaticanCity/vatican-city.html",  },
    "Venezuela": { description: "Venezuela is a country on the northern coast of South America with diverse natural attractions. Along its Caribbean coast are tropical resort islands including Isla de Margarita and the Los Roques archipelago. To the northwest are the Andes Mountains and the colonial town of Mérida, a base for visiting Sierra Nevada National Park. Caracas, the capital, is to the north(Wikipedia)", cities: "Buenos Aires", name: "17q4-z-spc_HEckXhpFvVEt_Yi1UWQdhJ", place:"countries/Venezuela/venezuela.html",  },
  }
  var wrapper = $('#wrapper'), container;
  for (var key in countries){
     
   
      container = $('<div id="countries" class="container"></div>');
      wrapper.append(container);
      container.append('<div class="country">' + key +'</div>');
      container.append('<div class="images">' + `<a href="https://drive.google.com/uc?export=view&id=${countries[key].name}"><img src="https://drive.google.com/uc?export=view&id=${countries[key].name}">` + '</a>'  + '</div>');
      container.append('<div class="description">' + '<h2 class="h2">' + 'Description' + '</h2>' + countries[key].description  +'</div>' );
      container.append('<div class="btn-position">' + `<a class="button" href="${countries[key].place}">` + 'Learn more' + '</a>' + '</div>');
  }



function myFunction() {
  var x = document.getElementById("name");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }

} 
var myArray = []; 

for(var key in countries) {
    myArray.push(key);
}


var wrap = $('#wrap'), middle;

function getRandomValue() {


  var rand = myArray[Math.floor(Math.random() * myArray.length)];

// middle = $('<div class="middle"></div>');

var middle =$('#city'); 

wrap.append(middle);
middle.empty().append('<div id="name">' + rand +'</div>' + `<a class="button" href="${countries[rand].place}">` + 'Learn more' + '</a>' + '</div>' );
console.log(rand);

}

